### ISSUE TITLE
Prompt hangs when docker server connection drops

### ISSUE THREAD

**Issue by so0k** [adrianmo/powerline-docker#6]
Is it possible to reduce the timeout as the prompt becomes almost unusable as soon as the connection to the docker host is lost:

```2016-11-09 10:35:37,851:ERROR:shell:docker:UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)```

this means that prompts only show up after 60 seconds

**Comment by adrianmo** [comment]
@so0k I have reduced the timeout to 2 seconds by default. It can now be configured to any other value if needed.

Please update to v1.0.4 to take advantage of this.

Also, make sure you are using [`powerline-daemon`](https://github.com/kovidgoyal/powerline-daemon) to speed up powerline segments processing.

This Powerline segment (powerline-docker) works better as a Tmux segment rather than a Shell segment. Because this way it does not need to connect with the Docker engine at every command.

Please feel free to reopen this issue if your problem persists.

Best,

-Adrian
